services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Sitemap\SitemapProviderInterface:
            tags: ['sitemap.provider']

    Mindy\Bundle\SitemapBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Sitemap\Builder:
        arguments:
            - 'https://example.com'
            - '%kernel.project_dir%/public'
